### ISSUE TITLE
config files

### ISSUE THREAD

**Issue by ghost** [ckardaris/ucollage#10]
There is any config file to create shortcuts to auto-run scripts or commands?
Also, if I like to start the tool in a specific view mode with say 1 column only is that possible?
Last it allays ask to expand pictures! can this be remove?

**Comment by ckardaris** [comment]
>There is any config file to create shortcuts to auto-run scripts or commands?

Currently this is not possible if I understand you correctly. But I'm always thinking about ways to improve the program. I will do more work on it soon.

>Also, if I like to start the tool in a specific view mode with say 1 column only is that possible?

Check variables `UCOLLAGE_LINES` and `UCOLLAGE_COLUMNS`.

>Last it allays ask to expand pictures! can this be remove?

Check variable `UCOLLAGE_EXPAND_DIRS`

**Comment by ghost** [comment]
> Currently this is not possible if I understand you correctly. But I'm always thinking about ways to improve the program. I will do more work on it soon.

A config file will take this to the next level in my opinion, now I am using a script to run this command:
**feh --bg-scale $1 && cp $1 ~/.config/wall.png**  that get executed by running **script %s** on an image.

> Check variables UCOLLAGE_LINES and UCOLLAGE_COLUMNS.

_Nice Workaround Thanks._

> Check variable UCOLLAGE_EXPAND_DIRS

_This one did work changing it to -1._ 



Thanks a lot @ckardaris. Great Tool.

**Comment by ckardaris** [comment]
>A config file will take this to the next level in my opinion, now I am using a script to run this command:
`feh --bg-scale $1 && cp $1 ~/.config/wall.png` that get executed by running script %s on an image.

This is interesting. A config with the most used scripts. I will think of an elegant way to include it in the next version.

**Comment by ghost** [comment]
How about an function to create custom shortcuts inside a config file style for command execution or scripts also like:
`set (shortcut) executed command or script`
So one selects an image plus the shortcut to execute configured command or script on it.

In this  particular case I am using now I could do:
`set w feh --bg-scale %s && cp %s ~/.config/wall.png`
Where pressing an x number image Plus w automatically set the image as background.

I could think of many uses for something like that.. as right now i am using ucollage as default I3wm wallpaper chooser.

![ucollage](https://user-images.githubusercontent.com/18301363/107723472-f29f1f80-6cbf-11eb-9598-edbaca71a729.png)

**Comment by ckardaris** [comment]
Yes, this is possible. As of now, I am writing ideas about what to implement with my next release. And your suggestion opens up many possibilities. You can **watch**  the repo and get informed when these new changes are included in my code. Thanks for your interest and, again, I apologize for not being able to implement your suggestions right away.
