### ISSUE TITLE
undocumented Left/Right keys in monocle and default modes doing critical tasks 

### ISSUE THREAD

**Issue by HiTuX** [ckardaris/ucollage#11]
Hi,
Thank you for this amazing software.

I just testing this and  surprised that the`Left` key in monocle mode is "Succefully deleting" my pictures!  Fortunately, it is only sending them to `./local/share/Trash/ucollage/`. I found that this behavior is undocumented and tricky.  `Left` key , for a newcomer, si expected to go to the previous image, but in ucollage it is deleting images and gives /'wrong'/ message: "succefully deleted" which, IMHO, should be more verbose, like: `Image <name> sent to trash folder at <PATH>"

In default (or grid/thumbnails whatever) mode Left/Right/Down keys ask for input to delete/rename/exectude a command. I think this is confusing and these keys should be kept for navigation as expected on vim/emacs/most softwares.

One more thing, it would be nice if  a confirmation message is shown before deleting/moving to trash an image or at least make it configurable.

Keep up the good work.

**Comment by ckardaris** [comment]
>One more thing, it would be nice if a confirmation message is shown before deleting/moving to trash an image or at least make it configurable.

If you check the configuration variables there is one that does exactly that. `UCOLLAGE_EXEC_PROMPT`. It should be working.

Regarding everything else, I can understand your frustration. Currently I don't have the time to make any modifications to the code, but I will dive into any issues soon. Until then I ask for your patience.
