### ISSUE TITLE
[Feature request] Option to load image sorted by modified date

### ISSUE THREAD

**Issue by KevCui** [ckardaris/ucollage#6]
Using ucollage to open all images in a folder, the current behavior is to load all images sorted alphabetically by file name. It would be great to have another option to sort files by modified date, the most recent modified one showing at the first place.

**Comment by ckardaris** [comment]
We could do something like
```bash
filelist=($(ls -c "$@"))
```

**Comment by ckardaris** [comment]
@KevCui Do you want to work on this?

**Comment by KevCui** [comment]
@ckardaris Sure, I'll try, but not promise that it will be done soon 🙂

**Comment by ckardaris** [comment]
Ok, we should have an exported variable `UCOLLAGE_SORT` with accepted values {name, time and anything else}
You should modify the `README` at the end and the relevant parts in functions `parse_config` and `set_defaults`
